### ISSUE TITLE
Feature-Request

### ISSUE THREAD

**Issue by sigi2345** [Patrick-Walther/ioBroker.iceroad#1]
Hallo,

Habe einige Wünsche:

Abfrageintervall zum selbst einstellen in Adapter Config integrieren

E-Mail Versand

2.Standort (für Familienmitglied)

Alle Datenpunkte

Grüße 
Sigi

**Comment by Patrick-Walther** [comment]
Hallo,

Bitte denk dran das der Adapter nur sagt, wann die Frontscheibe verreist ist.

Welche Datenpunkte Fehlen dir?(müssten alle vorhanden sein).
Wie meinst du eine zweiten Standort? (Wo kommt der zweite Standort her?)

Grüße

**Comment by sigi2345** [comment]
> Hallo,
> 
> Bitte denk dran das der Adapter nur sagt, wann die Frontscheibe verreist ist.
OK

> 
> Welche Datenpunkte Fehlen dir?(müssten alle vorhanden sein). 

Schlüssel | Typ | Beschreibung
-- | -- | --
success | boolean | War die Anfrage erfolgreich?
message | string | Fehler- oder Erfolgsmeldung
callsLeft | int | Für heute übrige Abfragen
callsDailyLimit | int | Tägliches Kontingent an API Abfragen
callsResetInSeconds | int | Sekunden bis zum nächsten Tag und Auffrischung des Kontingents


Wie meinst du eine zweiten Standort? (Wo kommt der zweite Standort her?)

Ok, kann ja auch eine 2. Instanz hinzu fügen

> 
> Grüße

**Comment by sigi2345** [comment]
Das kennst du?

https://www.smarthome-tricks.de/software-iobroker/eiswarnung-per-blockly-in-iobroker-auswerten/?fbclid=IwAR2vsDOoelo6D4ost7dr1ydxAyl3B_97YmWWxgbhJCtmWt52pSFV_T-AwFs

**Comment by Patrick-Walther** [comment]
Kann dir gerne mehrere Felder in ein Adapter machen.

Den Link kenne ich. Hatte schonmal eine Version mit allen Datenpunkte, werde die wieder hochladen.

Wünschst du eine Mail Adresse oder mehrerer?

Grüße

**Comment by sigi2345** [comment]
> Kann dir gerne mehrere Felder in ein Adapter machen.
> 
> Den Link kenne ich. Hatte schonmal eine Version mit allen Datenpunkte, werde die wieder hochladen.
> 
> Wünschst du eine Mail Adresse oder mehrerer?

Mehrere wäre Cool als Option.

LG
Sigi

**Comment by Patrick-Walther** [comment]
Hi Sigi,
möchtest du dein E-Mail Text frei wählen. Soll bei jedem Schedule eine Mail versendet werden?

Grüße

**Comment by sigi2345** [comment]
> Hi Sigi, möchtest du dein E-Mail Text frei wählen.

Bitte


 Soll bei jedem Schedule eine Mail versendet werden?

Nein, nur bei Eis Warnung


Grüße

**Comment by Patrick-Walther** [comment]
Morgen oder Übermorgen kommt das Update!
